### ISSUE TITLE
opportunità di un processo di call back

### ISSUE THREAD

**Issue by marcocipri** [AgID/lg-interop-update#12]
se abbiamo compreso bene il processo, il fruitore, una volta effettuata la richiesta, dovrà chiedere in modalità "polling" la disponibilità del dato dando origine ad un potenziale volume di richieste inutile.
non sarebbe opportuno prevedere un processo di callback da parte dell'erogatore che notifica la disponibilità del dato, e la chiusura delle sue elaborazioni, al fruitore?
questo potrebbe permettere una comunicazione più efficiente ed una integrazione migliore con PDND?

**Comment by jackom83** [comment]
La proposta di pattern individuata risponde all'esigenza di definire modalità tecniche per il recupero di risorse in maniera massiva, attraverso la gestione di richieste/risposte parziali, ciò indipendentemente dalla modalità con cui la risorsa in oggetto è resa disponibile. Di specie per risorse immediatamente disponibili, il pattern è direttamente applicabile, per risorse costruite dinamicamente a partire dalla richiesta è necessario l'utilizzo di pattern asincroni gia presenti nel framework del ModI.

La ringraziamo comunque per lo spunto di riflessione, ed cogliamo l'occasione per invitare le pubbliche amministrazioni ad indicarci eventuali esigenze in tal senso secondo le modalità previste dal Cap 6 delle Linee guida sull’interoperabilità tecnica delle Pubbliche Amministrazioni, e come indicato anche nella sezione relativa del sito dell'Agenzia ( https://www.agid.gov.it/it/infrastrutture/sistema-pubblico-connettivita/il-nuovo-modello-interoperabilita/governance-del-modello  )
