### ISSUE TITLE
Richiesta Chiarimenti su profilo [AUDIT_REST_02]

### ISSUE THREAD

**Issue by vmarchese** [AgID/lg-interop-update#8]
### Contesto 
Proposal [[AUDIT_REST_02] Inoltro dati tracciati nel dominio del Fruitore REST con correlazione](https://github.com/AgID/lg-interop-update/blob/main/proposals/request002/request002_proposal002.rst)

### Dettagli
Fra i passi per richiedere il Voucher alla PDND, è elencato lo step: 

_"2. predisporre la rappresentazione opaca dei dati tracciati e firmati (digest del JWS di audit) ed inserirla nella Access Token Request alla Piattaforma Digitale Nazionale Dati per l’interoperabilità;"_

Riportato similarmente nelle [Regole di Processamento](https://github.com/AgID/lg-interop-update/blob/main/proposals/request002/request002_proposal002.rst#regole-di-processamento) al punto A.3

### Richiesta 

Non è chiaro dove vada inserita la rappresentazione opaca dei dati tracciati (e.g. digest del JWS) nella richiesta di access token.
A esempio, se vada inserita nella `client_assertion` e, se sì, in quale `claim` della stessa

**Comment by vintra73** [comment]
Le segnalo che il dettaglio implementativo sarà esplicitato nell'ambito delle specifiche tecniche della PDND Interoperabilità in cui, nello specifico, sarà individuato il claim all'interno della client assertion in cui posizionare il **digest del JWS di audit**.

**Comment by vmarchese** [comment]
Grazie, chiudo la Issue da parte mia
