### ISSUE TITLE
Richiesta Chiarimenti su profilo [AUDIT_REST_02] "dnonce" e politiche di caching

### ISSUE THREAD

**Issue by vmarchese** [AgID/lg-interop-update#9]
### Contesto

Proposal [[AUDIT_REST_02] Inoltro dati tracciati nel dominio del Fruitore REST con correlazione](https://github.com/AgID/lg-interop-update/blob/main/proposals/request002/request002_proposal002.rst)

Utilizzo da elevato numero di postazioni del fruitore e politiche di caching

### Dettagli

Nella costruzione del JWS di Audit è richiesto l'inserimento di un `dnonce` definito come numero casuale di 13 cifre per aumentare l'entropia.

### Richiesta

In caso di elevato numero di postazioni e per la correlazione fra richiesta Access Token, Access Token stesso e JWS di Audit, la generazione di un `dnonce`  randomico per ogni richiesta non permette il caching dell'Access Token generato causando un carico aggiuntivo sia sul chiamante (fruitore che per ogni API call deve richiedere un nuovo Access Token alla PDND) che sulla PDND.

Si richiede di chiarire la possibilità di riuso dell'Access Token e, conseguentemente, del JWS di Audit (che, a parte il `dnonce` non ha dati variabili per richiesta)

**Comment by vintra73** [comment]
Sulla base della sua abbiamo migliorato il writing del pattern per chiarire che la generazione del JWS di audit non è prevista per ogni Access Token Request alla PDND ma dipende dalla validità nel dominio del Fruitore dei dati in esso contenuti.

Vedi commit ef48a19ef47f306c342dc7d9cae664c549dda28d

**Comment by vmarchese** [comment]
Grazie, chiudo la issue da parte mia
